(function(){
 'use strict';
 let goals=[],owner='',filter='all',editing=null,expenseId=null,previewDemand=null,loading=0;
 const el=id=>document.getElementById(id),esc=value=>escapeHTML(String(value??''));
 const icon=(kind)=>`<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${kind==='edit'?'<path d="m16 3 5 5-12 12-6 1 1-6Z"/><path d="m14 5 5 5"/>':'<circle cx="12" cy="12" r="9"/><circle cx="12" cy="12" r="5"/><circle cx="12" cy="12" r="1"/>'}</svg>`;
 const frame=(id,title,body,footer)=>`<div class="overlay" id="${id}" onclick="if(event.target===this)closeModal('${id}')"><div class="modal finance-modal"><div class="m-head"><div class="m-title" id="${id}-title">${title}</div><button type="button" class="m-close" aria-label="Fechar" onclick="closeModal('${id}')">✕</button></div><div class="m-body">${body}</div><div class="m-foot">${footer}</div></div></div>`;
 const field=(id,label,input)=>`<div class="fg"><label class="fl" for="${id}">${label}</label>${input}</div>`;
 const input=(id,type='text',extra='')=>`<input class="fi" id="${id}" type="${type}" ${extra}>`;
 const cancel=id=>`<button type="button" class="btn btn-ghost" onclick="closeModal('${id}')">Cancelar</button>`;
 window.clearGoalsState=function(){loading++;goals=[];owner='';editing=null;expenseId=null;previewDemand=null;const grid=el('goals-grid'),summary=el('goals-summary');if(grid)grid.innerHTML='';if(summary)summary.innerHTML='';};
 document.body.insertAdjacentHTML('beforeend',
 frame('modal-goal','Nova meta',
 field('g-title','Nome da meta',input('g-title','text','maxlength="160" placeholder="Ex.: Fechar 3 planos Supreme"'))+
 field('g-metric','Como acompanhar',`<select class="fi" id="g-metric" onchange="syncGoalFields()"><option value="revenue">Faturamento · automático</option><option value="count">Vendas / planos fechados · automático</option><option value="manual">Objetivo livre · atualização manual</option></select>`)+
 `<div class="goal-editor-help" id="g-rule"></div><div class="f2">`+
 field('g-target','Valor da meta',input('g-target','number','min="0.01" step="0.01" max="999999999999.99" placeholder="15000"'))+
 field('g-unit','Unidade',input('g-unit','text','maxlength="40" placeholder="Ex.: entregas, reuniões, %"'))+`</div>`+
 field('g-plan','Plano / pacote',`<select id="g-plan" class="fi"></select>`)+
 `<div class="goal-date-presets" role="group" aria-label="Período da meta"><button class="btn btn-ghost btn-sm" onclick="setGoalPeriod('day')">Diária</button><button class="btn btn-ghost btn-sm" onclick="setGoalPeriod('week')">Semanal</button><button class="btn btn-ghost btn-sm" onclick="setGoalPeriod('month')">Mensal</button><span>Ou escolha as datas</span></div><div class="f2">`+
 field('g-start','Início',input('g-start','date'))+field('g-end','Prazo',input('g-end','date'))+`</div>`+
 field('g-description','Observações (opcional)',`<textarea class="fi" id="g-description" maxlength="2000" placeholder="Contexto, próximos passos ou critérios de sucesso"></textarea>`),
 cancel('modal-goal')+`<button class="btn btn-primary" id="goal-save" onclick="saveGoal()">Salvar meta</button>`)+
 frame('modal-goal-progress','Atualizar progresso',`<p id="goal-progress-title"></p>`+field('g-current','Total realizado até agora',input('g-current','number','min="0" step="0.01" max="999999999999.99"')),cancel('modal-goal-progress')+`<button class="btn btn-primary" id="goal-progress-save" onclick="saveGoalProgress()">Salvar progresso</button>`)+
 frame('modal-expense','Adicionar gasto',field('e-title','Descrição do gasto',input('e-title','text','maxlength="160" placeholder="Ex.: Software, anúncios, fornecedor"'))+`<div class="f2">`+field('e-value','Valor (R$)',input('e-value','number','min="0.01" step="0.01" max="999999999999.99"'))+field('e-date','Data do gasto',input('e-date','date'))+`</div>`+field('e-assignee','Responsável',`<select class="fi" id="e-assignee"></select>`)+field('e-notes','Observações (opcional)',`<textarea id="e-notes" class="fi" maxlength="2000"></textarea>`)+`<div class="goal-editor-help">O gasto é descontado da receita fechada no período da data informada.</div>`,cancel('modal-expense')+`<button class="btn btn-primary" id="expense-save" onclick="saveExpense()">Salvar gasto</button>`)+
 frame('modal-sales-period','Período personalizado',`<div class="f2">`+field('sp-from','Data inicial',input('sp-from','date'))+field('sp-to','Data final',input('sp-to','date'))+`</div>`,cancel('modal-sales-period')+`<button class="btn btn-primary" onclick="applyCustomSalesPeriod()">Aplicar período</button>`)+
 frame('modal-sale-demand','Demanda vinculada',`<div id="sale-demand-preview"></div>`,`<button class="btn btn-ghost" onclick="closeModal('modal-sale-demand')">Fechar</button><button id="sale-demand-edit" class="btn btn-primary" onclick="editSaleDemandPreview()">${icon('edit')} Editar demanda</button>`));

 async function allRows(table,select,order='id'){
  const rows=[];for(let offset=0;;offset+=1000){const {data,error}=await supa.from(table).select(select).order(order).order('id').range(offset,offset+999);if(error)throw error;rows.push(...data);if(data.length<1000)return rows;}
 }
 window.fetchFullSales=async function(){try{return {data:await allRows('sales','*, clients(name), plans(name)','created_at'),error:null};}catch(error){return {data:null,error};}};
 function state(g){const today=MagemindCore.civilDate();return g.archived?'archived':Number(g.current_value)>=Number(g.target)?'achieved':today<g.start_date?'scheduled':today>g.end_date?'missed':'active';}
 const labels={archived:'Arquivada',achieved:'Atingida',scheduled:'Programada',missed:'Prazo encerrado',active:'Em andamento'};
 function fmt(g,v){return g.metric==='revenue'?formatCurrencyBRL(v):Number(v).toLocaleString('pt-BR')+' '+(g.metric==='count'?(Number(v)===1?'venda':'vendas'):esc(g.unit));}
 window.loadGoals=async function(){
  const request=++loading;if(!isAdmin()){goals=[];owner='';el('goals-grid').innerHTML='';return;}
  const user=DB.me.id;if(owner!==user){goals=[];owner=user;filter='all';el('goals-search').value='';}
  el('goals-grid').setAttribute('aria-busy','true');if(!goals.length)el('goals-grid').innerHTML='<div class="goals-empty">Carregando metas...</div>';
  try{const rows=await allRows('goal_progress','*','end_date');if(request!==loading||DB.me?.id!==user||!isAdmin())return;goals=rows;renderGoals();}
  catch(error){if(request===loading){el('goals-grid').innerHTML='<div class="goals-empty">Não foi possível carregar as metas.<button class="btn btn-ghost" onclick="loadGoals()">Tentar novamente</button></div>';toast('Erro ao carregar metas: '+error.message,'err');}}
  finally{if(request===loading)el('goals-grid').removeAttribute('aria-busy');}
 };
 window.setGoalFilter=function(value){filter=value;renderGoals();};
 window.renderGoals=function(){
  if(!isAdmin()||owner!==DB.me.id)return;
  const visible=goals.filter(g=>!g.archived),counts={active:visible.filter(g=>['active','scheduled'].includes(state(g))).length,achieved:visible.filter(g=>state(g)==='achieved').length,missed:visible.filter(g=>state(g)==='missed').length};
  el('goals-summary').innerHTML=Object.entries(counts).map(([key,n])=>`<div class="goal-summary"><span>${key==='active'?'No radar':key==='achieved'?'Metas atingidas':'Prazos encerrados'}</span><strong>${n}</strong><small>${key==='active'?'Ativas e programadas':key==='achieved'?'Resultado alcançado':'Revise os próximos passos'}</small></div>`).join('');
  document.querySelectorAll('[data-goal-filter]').forEach(b=>{b.classList.toggle('active',b.dataset.goalFilter===filter);b.setAttribute('aria-pressed',String(b.dataset.goalFilter===filter));});
  const search=el('goals-search').value.toLocaleLowerCase('pt-BR');
  const rows=goals.filter(g=>(filter==='all'?!g.archived:filter==='active'?['active','scheduled'].includes(state(g)):state(g)===filter)&&g.title.toLocaleLowerCase('pt-BR').includes(search));
  el('goals-grid').innerHTML=rows.length?rows.map(g=>{
    const s=state(g),current=Number(g.current_value),target=Number(g.target),remaining=Math.max(0,target-current),percent=Math.min(100,current/target*100);
    const days=Math.max(1,Math.floor((Date.parse(g.end_date+'T12:00Z')-Date.parse(MagemindCore.civilDate()+'T12:00Z'))/86400000)+1);
    return `<article class="goal-card ${s}"><div class="goal-card-top"><span class="goal-kind">${icon('target')}${g.metric==='revenue'?'Faturamento':g.metric==='count'?'Vendas fechadas':'Objetivo livre'}</span><button class="btn btn-ghost btn-xs sale-icon" aria-label="Editar meta ${esc(g.title)}" onclick="openGoal('${g.id}')">${icon('edit')}</button></div><h2>${esc(g.title)}</h2><span class="goal-state">${labels[s]}</span><div class="goal-amount"><strong>${fmt(g,current)}</strong><span>de ${fmt(g,target)}</span></div><div class="goal-track" role="progressbar" aria-label="Progresso de ${esc(g.title)}" aria-valuemin="0" aria-valuemax="100" aria-valuenow="${percent.toFixed(1)}"><span style="width:${percent}%"></span></div><div class="goal-progress-copy"><span>${remaining?'Restante: '+fmt(g,remaining):'Meta alcançada'}</span><strong>${Math.round(percent)}%</strong></div><div class="goal-period">${fDate(g.start_date)} → ${fDate(g.end_date)}</div>${g.plan_id?`<div class="goal-detail">${esc(g.plan_name)}</div>`:''}${g.description?`<p class="goal-description">${esc(g.description)}</p>`:''}<div class="goal-card-foot"><span>${g.metric==='manual'?'Atualização manual':s==='active'&&remaining?fmt(g,Math.ceil(remaining/days*(g.metric==='revenue'?100:1))/(g.metric==='revenue'?100:1))+' / dia para atingir':'Atualização automática pelas vendas'}</span><div>${g.metric==='manual'&&!g.archived?`<button class="btn btn-ghost btn-sm" onclick="openGoalProgress('${g.id}')">Atualizar</button>`:''}<button class="btn btn-ghost btn-sm" onclick="archiveGoal('${g.id}')">${g.archived?'Restaurar':'Arquivar'}</button></div></div></article>`;
   }).join(''):`<div class="goals-empty">${icon('target')}<h2>${goals.length?'Nenhuma meta neste filtro':'O próximo resultado começa aqui'}</h2><p>Defina o que quer alcançar e acompanhe cada avanço.</p><button class="btn btn-primary" onclick="openGoal()">Criar meta</button></div>`;
 };
 window.syncGoalFields=function(){const metric=el('g-metric').value;el('g-unit').closest('.fg').hidden=metric!=='manual';el('g-plan').closest('.fg').hidden=metric==='manual';el('g-target').step=metric==='count'?'1':'0.01';el('g-target').min=metric==='count'?'1':'0.01';el('g-rule').textContent=metric==='manual'?'Escolha uma unidade e atualize o total realizado quando avançar.':metric==='revenue'?'Soma automática das vendas fechadas entre o início e o prazo, até hoje. Gastos não reduzem o faturamento.':'Cada venda fechada conta uma vez no período. Selecione um plano específico ou todos.';};
 window.setGoalPeriod=function(period){const today=MagemindCore.civilDate();let start=today,end=today;if(period==='week'){const weekday=new Date(today+'T12:00Z').getUTCDay();start=MagemindCore.shiftDay(today,-((weekday+6)%7));end=MagemindCore.shiftDay(start,6);}if(period==='month'){start=today.slice(0,7)+'-01';const date=new Date(start+'T12:00Z');date.setUTCMonth(date.getUTCMonth()+1,0);end=date.toISOString().slice(0,10);}el('g-start').value=start;el('g-end').value=end;};
 window.openGoal=function(id){if(!isAdmin())return;editing=id?goals.find(g=>g.id===id):null;const g=editing;el('modal-goal-title').textContent=g?'Editar meta':'Nova meta';el('g-title').value=g?.title||'';el('g-metric').value=g?.metric||'revenue';el('g-target').value=g?.target||'';el('g-unit').value=g?.unit||'unidades';el('g-description').value=g?.description||'';el('g-plan').innerHTML='<option value="">Todos os planos</option>'+DB.plans.map(p=>`<option value="${p.id}">${esc(p.name)}${p.active?'':' (inativo)'}</option>`).join('');el('g-plan').value=g?.plan_id||'';setGoalPeriod('month');if(g){el('g-start').value=g.start_date;el('g-end').value=g.end_date;}syncGoalFields();openModal('modal-goal');};
 async function mutate(query){const {data,error}=await query.select().single();if(error)throw error;return data;}
 window.saveGoal=async function(){if(!isAdmin()||el('goal-save').disabled)return;const target=Number(el('g-target').value),metric=el('g-metric').value;const payload={title:el('g-title').value.trim(),metric,target,unit:metric==='manual'?el('g-unit').value.trim():'unidades',plan_id:metric==='manual'?null:el('g-plan').value||null,start_date:el('g-start').value,end_date:el('g-end').value,description:el('g-description').value.trim()};if(!payload.title||!payload.unit||!Number.isFinite(target)||target<=0||target>999999999999.99||!payload.start_date||!payload.end_date||payload.start_date>payload.end_date||(metric==='count'&&!Number.isInteger(target))){toast('Revise nome, valor, unidade e período da meta.','err');return;}const current=editing;el('goal-save').disabled=true;try{await mutate(current?supa.from('goals').update(payload).eq('id',current.id).eq('updated_at',current.updated_at):supa.from('goals').insert(payload));closeModal('modal-goal');await loadGoals();toast('Meta salva.','ok');}catch(error){toast('Não foi possível salvar. Reabra a meta se outra pessoa a alterou. '+error.message,'err');}finally{el('goal-save').disabled=false;}};
 window.openGoalProgress=function(id){if(!isAdmin())return;editing=goals.find(g=>g.id===id);if(!editing||editing.metric!=='manual')return;el('goal-progress-title').textContent=editing.title;el('g-current').value=editing.manual_value;openModal('modal-goal-progress');};
 window.saveGoalProgress=async function(){if(!isAdmin()||!editing||el('goal-progress-save').disabled)return;const value=Number(el('g-current').value),g=editing;if(el('g-current').value===''||!Number.isFinite(value)||value<0||value>999999999999.99){toast('Informe um total válido.','err');return;}el('goal-progress-save').disabled=true;try{await mutate(supa.from('goals').update({manual_value:value}).eq('id',g.id).eq('updated_at',g.updated_at));closeModal('modal-goal-progress');await loadGoals();toast('Progresso atualizado.','ok');}catch(error){toast('Não foi possível salvar. Reabra a meta para atualizar os dados.','err');}finally{el('goal-progress-save').disabled=false;}};
 window.archiveGoal=async function(id){if(!isAdmin())return;const g=goals.find(x=>x.id===id);if(!g)return;try{await mutate(supa.from('goals').update({archived:!g.archived}).eq('id',id).eq('updated_at',g.updated_at));await loadGoals();}catch(error){toast('Não foi possível atualizar a meta. Recarregue e tente novamente.','err');}};

 window.openNewExpense=()=>openExpense();
 window.openExpense=function(id){if(!isAdmin())return;expenseId=id||null;const e=DB.sales.find(s=>s.id===id);el('modal-expense-title').textContent=e?'Editar gasto':'Adicionar gasto';el('e-title').value=e?.service||'';el('e-value').value=e?.value||'';el('e-date').value=e?.date||MagemindCore.civilDate();el('e-notes').value=e?.desc||'';const names=[...new Set([e?.assignee||DB.me.name,...activeOperationalUsers().map(u=>u.name)].filter(Boolean))];el('e-assignee').innerHTML=names.map(n=>`<option value="${esc(n)}">${esc(n)}</option>`).join('');openModal('modal-expense');};
 window.saveExpense=async function(){if(!isAdmin()||el('expense-save').disabled)return;const value=Number(el('e-value').value),service=el('e-title').value.trim(),date=el('e-date').value;if(!service||!Number.isFinite(value)||value<=0||value>999999999999.99||!date){toast('Preencha a descrição, o valor e a data do gasto.','err');return;}const payload={status:'Gasto',client_id:null,plan_id:null,demand_id:null,service,value,sale_date:date,description:el('e-notes').value.trim(),assignee:el('e-assignee').value};el('expense-save').disabled=true;try{const saved=await mutate(expenseId?supa.from('sales').update(payload).eq('id',expenseId).eq('status','Gasto'):supa.from('sales').insert(payload));const i=DB.sales.findIndex(s=>s.id===saved.id);if(i<0)DB.sales.push(mapSale(saved));else DB.sales[i]=mapSale(saved);closeModal('modal-expense');loadSales();toast('Gasto salvo.','ok');}catch(error){toast('Não foi possível salvar o gasto: '+error.message,'err');}finally{el('expense-save').disabled=false;}};
 window.openSaleDemandPreview=async function(d){if(!canViewDemand(d))return;previewDemand=d;el('sale-demand-edit').hidden=!canEditDemand(d);el('sale-demand-preview').innerHTML=`<div class="sale-demand-heading">${stBadge(d.status)}${prBadge(d.priority)}<h2>${esc(d.title)}</h2></div><dl class="sale-demand-facts"><div><dt>Cliente</dt><dd>${esc(d.clientName||cn(d.client))}</dd></div><div><dt>Responsável</dt><dd>${esc(d.assignee||'Não atribuído')}</dd></div><div><dt>Entrega</dt><dd>${fDate(d.date)}</dd></div></dl><h3>Descrição</h3><p class="sale-demand-text">${esc(d.desc||'Sem descrição.')}</p>${d.refs?`<h3>Referências</h3><p class="sale-demand-text">${esc(d.refs)}</p>`:''}<h3>Comentários</h3><div id="sale-demand-comments">Carregando...</div>`;openModal('modal-sale-demand');const {data,error}=await supa.from('comments').select('text,created_at,profiles(name)').eq('demand_id',d.id).order('created_at');if(previewDemand?.id!==d.id)return;el('sale-demand-comments').innerHTML=error?'Não foi possível carregar os comentários.':data.length?data.map(c=>`<div class="sale-demand-comment"><strong>${esc(c.profiles?.name||'Equipe')}</strong><p class="sale-demand-text">${esc(c.text)}</p></div>`).join(''):'Nenhum comentário.';};
 window.editSaleDemandPreview=async function(){if(!previewDemand||!canEditDemand(previewDemand))return;closeModal('modal-sale-demand');await openDetail(previewDemand.id);};
 window.addEventListener('focus',()=>{if(typeof DB!=='undefined'&&DB.me&&isAdmin()&&el('pg-goals')?.classList.contains('active'))loadGoals();});
 setInterval(()=>{if(typeof DB!=='undefined'&&DB.me&&isAdmin()&&!document.hidden&&el('pg-goals')?.classList.contains('active'))loadGoals();},60000);
})();
