/* Partner finance: independent from referral commissions. All mutations use guarded RPCs. */
const PartnerState={owner:null,people:[],defaults:[],shares:[],withdrawals:[],wallet:null,tab:'sales',filter:'all',person:'all',loading:null,error:'',draft:[],withdrawKey:null};
const partnerIcon='<svg width="17" height="17" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" aria-hidden="true"><path d="m7 8 3-3h4l3 3 4 1-2 9-4 2-3-2-3 2-4-2-2-9 4-1Z"/><path d="m7 8 4 4 3-2 4 5M12 18l-5-5"/></svg>';
function partnerMoney(n){return formatCurrencyBRL(Number(n)||0);}
async function partnerRows(table){let out=[];for(let start=0;;start+=1000){const {data,error}=await supa.from(table).select('*').order(table==='partner_defaults'?'partner_id':'id').range(start,start+999);if(error)throw error;out.push(...(data||[]));if(!data||data.length<1000)return out;}}
async function loadPartnerData(){
 if(!DB.me||(!isAdmin()&&!isPartner()))return;
 const uid=DB.me.id;
 if(PartnerState.loading&&PartnerState.owner===uid)return PartnerState.loading;
 if(PartnerState.owner!==uid){Object.assign(PartnerState,{owner:uid,people:[],defaults:[],shares:[],withdrawals:[],wallet:null,person:'all',tab:isAdmin()?'partners':'sales',loading:null});}
 PartnerState.loading=(async()=>{
  const results=await Promise.all([partnerRows('partner_defaults'),partnerRows('partner_sale_shares'),partnerRows('partner_withdrawals'),isAdmin()?supa.from('profiles').select('id,name,active,archived_at,role').eq('role','partner'):Promise.resolve({data:[DB.me]}),isPartner()?supa.rpc('get_partner_wallet'):Promise.resolve({data:null})]);
  if(DB.me?.id!==uid)return;
  if(results[3].error)throw results[3].error;if(results[4].error)throw results[4].error;
  [PartnerState.defaults,PartnerState.shares,PartnerState.withdrawals]=results;
  PartnerState.people=results[3].data||[];PartnerState.wallet=results[4].data;PartnerState.error='';
 })();
 try{await PartnerState.loading;}catch(error){PartnerState.error=error.message||'Não foi possível carregar as participações.';throw error;}finally{PartnerState.loading=null;}
}
async function refreshPartnerPanel(){
 try{await loadPartnerData();if(isAdmin()){renderTeamPartners();renderUnifiedWithdrawals();}if(document.getElementById('pg-partners')?.classList.contains('active'))renderPartners();if(isPartner()&&document.getElementById('pg-dashboard')?.classList.contains('active'))renderPartnerHome();}catch(error){console.error('[Parceiros]',error);if(isPartner()&&document.getElementById('pg-dashboard')?.classList.contains('active'))renderPartnerHome();if(document.getElementById('pg-partners')?.classList.contains('active'))renderPartners();}
}
async function loadPartners(){
 if(isAdmin()){goTo('team');return;}
 document.getElementById('partners-content').innerHTML='<div class="partner-empty" role="status">Carregando seu financeiro…</div>';
 await refreshPartnerPanel();
}
function partnerMetrics(){
 if(isPartner()&&PartnerState.wallet)return PartnerState.wallet;
 const p=PartnerState.person,shares=PartnerState.shares.filter(s=>p==='all'||s.partner_id===p),w=PartnerState.withdrawals.filter(w=>p==='all'||w.partner_id===p);
 const sum=(rows)=>rows.reduce((a,r)=>a+Math.round(Number(r.amount)*100),0)/100;
 const earned=sum(shares.filter(s=>s.state==='available')),reserved=sum(w.filter(w=>['pending','approved'].includes(w.status))),paid=sum(w.filter(w=>w.status==='paid'));
 return {earned,reserved,paid,available:earned-reserved-paid,pending:sum(shares.filter(s=>s.state==='pending'))};
}
function partnerStats(){const w=partnerMetrics();return `<div class="partner-stats">${[['Disponível para saque',w.available,'Saldo liberado, sem valores reservados','highlight'],['A receber',w.pending,'Participações em vendas pendentes',''],['Em solicitação',w.reserved,'Saques pendentes ou aprovados',''],['Recebido',w.paid,'Pagamentos registrados','']].map(([title,value,hint,cls])=>`<div class="partner-stat ${cls}"><span>${title}</span><strong class="financial-value">${partnerMoney(value)}</strong><small>${hint}</small></div>`).join('')}</div>`;}
function partnerBadge(state,withdrawal=false){const names={pending:withdrawal?'Em análise':'A receber',available:'Disponível',cancelled:'Cancelada',approved:'Aprovado',paid:'Pago',rejected:'Recusado',reversed:'Estornado'};return `<span class="badge ${state==='available'||state==='paid'?'b-emerald':state==='pending'||state==='approved'?'b-amber':'b-muted'}">${names[state]||escapeHTML(state)}</span>`;}
function partnerSalesHTML(limit){
 const rows=PartnerState.shares.filter(s=>(!isAdmin()||PartnerState.person==='all'||s.partner_id===PartnerState.person)&&(PartnerState.filter==='all'||s.state===PartnerState.filter)).sort((a,b)=>String(b.sale_date||'').localeCompare(String(a.sale_date||''))||String(b.updated_at).localeCompare(String(a.updated_at)));
 return rows.length?`<div class="partner-list">${(limit?rows.slice(0,limit):rows).map(s=>`<article class="partner-sale"><div><strong>${escapeHTML(s.sale_label)}</strong><p>${escapeHTML(s.client_label)} · ${fDate(s.sale_date)}</p>${isAdmin()?`<small>${escapeHTML(s.partner_name)}</small>`:''}</div><div><span>Venda de ${partnerMoney(s.base_value)}</span><p>Sua participação: ${Number(s.rate).toLocaleString('pt-BR')}%</p></div><div class="partner-sale-value"><strong class="financial-value">${partnerMoney(s.amount)}</strong>${partnerBadge(s.state)}</div></article>`).join('')}</div>`:'<div class="partner-empty">Nenhuma venda vinculada neste filtro.</div>';
}
function partnerWithdrawalHTML(){
 const rows=PartnerState.withdrawals.filter(w=>!isAdmin()||PartnerState.person==='all'||w.partner_id===PartnerState.person).sort((a,b)=>String(b.requested_at).localeCompare(String(a.requested_at)));
 return rows.length?`<div class="partner-list">${rows.map(w=>`<article class="partner-withdrawal"><div><strong>${partnerMoney(w.amount)}</strong> ${partnerBadge(w.status,true)}<p>${isAdmin()?escapeHTML(w.partner_name)+' · ':''}${new Date(w.requested_at).toLocaleString('pt-BR')}</p><small>Pix (${escapeHTML(w.pix_key_type)}): ${escapeHTML(w.pix_key)}</small>${w.note?`<p>${escapeHTML(w.note)}</p>`:''}</div><div class="partner-actions">${isAdmin()?`${w.status==='pending'?`<button class="btn btn-primary btn-sm" onclick="openPartnerReview('${w.id}','approve')">Aprovar</button>`:''}${w.status==='approved'?`<button class="btn btn-primary btn-sm" onclick="openPartnerReview('${w.id}','pay')">Registrar pagamento</button>`:''}${['pending','approved'].includes(w.status)?`<button class="btn btn-ghost btn-sm" onclick="openPartnerReview('${w.id}','reject')">Recusar</button>`:''}${w.status==='paid'?`<button class="btn btn-ghost btn-sm" onclick="openPartnerReview('${w.id}','reverse')">Estornar registro</button>`:''}`:w.status==='pending'?`<button class="btn btn-ghost btn-sm" onclick="openPartnerReview('${w.id}','cancel')">Cancelar solicitação</button>`:''}</div></article>`).join('')}</div>`:'<div class="partner-empty">Nenhuma solicitação de saque ainda.</div>';
}
function partnerDefaultsHTML(){return `<p class="partner-help">O primeiro parceiro começa com 50% nas novas vendas. Outros parceiros podem ser incluídos por venda ou ativados como padrão. As vendas antigas mantêm suas divisões.</p><div class="partner-list">${PartnerState.people.map(p=>{const d=PartnerState.defaults.find(d=>d.partner_id===p.id)||{rate:50,enabled:false};return `<article class="partner-default"><div><strong>${escapeHTML(p.name)}</strong><p>${p.archived_at?'Arquivado':p.active?'Ativo':'Inativo'}</p></div><label class="fg"><span class="fl">Percentual padrão</span><input class="fi" type="number" min="0.01" max="100" step="0.01" value="${Number(d.rate)}" id="partner-rate-${p.id}" aria-label="Percentual de ${escapeHTML(p.name)}"></label><label class="partner-check"><input type="checkbox" id="partner-default-${p.id}" ${d.enabled?'checked':''}> Incluir em novas vendas</label><button class="btn btn-primary btn-sm" ${p.archived_at?'disabled':''} onclick="savePartnerDefault('${p.id}',this)">Salvar</button></article>`;}).join('')||'<div class="partner-empty">Cadastre um usuário com o cargo Parceiro na seção Equipe.</div>'}</div>`;}
function renderPartners(){
 const admin=isAdmin();document.getElementById('partners-title').textContent=admin?'Parceiros':'Carteira';
 document.getElementById('partners-sub').textContent=admin?'Participações na produção e solicitações de saque':'Suas participações, saldo e pagamentos em um só lugar';
 if(PartnerState.error){document.getElementById('partners-content').innerHTML=`<div class="partner-empty" role="alert">${escapeHTML(PartnerState.error)}<br><button class="btn btn-ghost" onclick="loadPartners()">Tentar novamente</button></div>`;return;}
 const tabs=admin?[['partners','Parceiros'],['sales','Vendas vinculadas'],['withdrawals','Saques']]:[['sales','Vendas vinculadas'],['withdrawals','Meus saques']];
 document.getElementById('partners-content').innerHTML=`${partnerStats()}<div class="partner-toolbar"><p class="partner-help">Saldos acumulados de todo o período. Vendas fechadas liberam a participação.</p>${admin?`<label class="fg"><span class="sr-only">Filtrar parceiro</span><select class="fi" aria-label="Filtrar parceiro" onchange="PartnerState.person=this.value;renderPartners()"><option value="all">Todos os parceiros</option>${PartnerState.people.map(p=>`<option value="${p.id}" ${PartnerState.person===p.id?'selected':''}>${escapeHTML(p.name)}</option>`).join('')}</select></label>`:`<button class="btn btn-primary" onclick="openPartnerWithdrawal()" ${Number(partnerMetrics().available)<1?'disabled':''}>Solicitar saque</button>`}</div><div class="partner-tabs" role="group" aria-label="Visualização do financeiro">${tabs.map(([id,label])=>`<button class="btn ${PartnerState.tab===id?'btn-primary':'btn-ghost'}" aria-pressed="${PartnerState.tab===id}" onclick="PartnerState.tab='${id}';renderPartners()">${label}${id==='withdrawals'&&admin?' · '+PartnerState.withdrawals.filter(w=>w.status==='pending').length:''}</button>`).join('')}</div>${PartnerState.tab==='partners'&&admin?partnerDefaultsHTML():PartnerState.tab==='withdrawals'?partnerWithdrawalHTML():`<div class="partner-toolbar"><h3>Participações por venda</h3><select class="fi" aria-label="Situação das participações" onchange="PartnerState.filter=this.value;renderPartners()">${[['all','Todas as situações'],['available','Disponível'],['pending','A receber'],['cancelled','Canceladas']].map(([v,t])=>`<option value="${v}" ${PartnerState.filter===v?'selected':''}>${t}</option>`).join('')}</select></div>${partnerSalesHTML()}`}`;
}
async function savePartnerDefault(id,button){button.disabled=true;try{const {error}=await supa.rpc('set_partner_default',{p_id:id,p_rate:Number(document.getElementById('partner-rate-'+id).value),p_enabled:document.getElementById('partner-default-'+id).checked});if(error)throw error;await refreshPartnerPanel();toast('Padrão atualizado para as próximas vendas.','ok');}catch(e){toast(e.message,'err');}finally{button.disabled=false;}}
async function loadDashPartner(){renderPartnerHome();await refreshPartnerPanel();}

async function preparePartnerSale(id){
 await loadPartnerData();
 PartnerState.draft=id?PartnerState.shares.filter(s=>s.sale_id===id&&s.included).map(s=>({partner_id:s.partner_id,rate:Number(s.rate)})):PartnerState.defaults.filter(d=>d.enabled&&PartnerState.people.some(p=>p.id===d.partner_id&&p.active&&!p.archived_at)).map(d=>({partner_id:d.partner_id,rate:Number(d.rate)}));
 renderPartnerSale();
}
function renderPartnerSale(){
 const host=document.getElementById('sale-partner-splits');
 host.innerHTML=`<div class="partner-toolbar"><div><h3>Divisão desta venda</h3><p class="partner-help">Remova quem não participa desta produção. A indicação é calculada separadamente.</p></div><button type="button" class="btn btn-ghost btn-sm" onclick="addSalePartner()">+ Parceiro</button></div><div class="partner-split-list">${PartnerState.draft.map((d,i)=>`<div class="partner-split-row"><select class="fi" aria-label="Parceiro ${i+1}" onchange="PartnerState.draft[${i}].partner_id=this.value;updatePartnerSplitSummary()"><option value="">Selecionar parceiro</option>${PartnerState.people.filter(p=>(p.active&&!p.archived_at)||p.id===d.partner_id).map(p=>`<option value="${p.id}" ${p.id===d.partner_id?'selected':''}>${escapeHTML(p.name)}</option>`).join('')}</select><label><input class="fi" type="number" min="0.01" max="100" step="0.01" value="${d.rate}" aria-label="Percentual do parceiro ${i+1}" oninput="PartnerState.draft[${i}].rate=Number(this.value);updatePartnerSplitSummary()"><span>%</span></label><button type="button" class="btn btn-ghost" aria-label="Remover parceiro ${i+1} desta venda" onclick="PartnerState.draft.splice(${i},1);renderPartnerSale()">✕</button></div>`).join('')||'<p class="partner-help">Sem participação de parceiros nesta venda.</p>'}</div><div id="sale-partner-summary" class="partner-split-summary" aria-live="polite"></div>`;
 updatePartnerSplitSummary();
}
function addSalePartner(){const p=PartnerState.people.find(p=>p.active&&!p.archived_at&&!PartnerState.draft.some(d=>d.partner_id===p.id));if(!p){toast('Cadastre outro parceiro ativo na Equipe.','err');return;}const d=PartnerState.defaults.find(d=>d.partner_id===p.id);PartnerState.draft.push({partner_id:p.id,rate:Number(d?.rate||50)});renderPartnerSale();}
function getPartnerSplitSummary(){
 const value=Number(document.getElementById('s-value').value)||0,client=DB.clients.find(c=>c.id===document.getElementById('s-client').value),ref=DB.users.find(u=>u.id===client?.affiliateId),existing=(DB.commissions||[]).find(c=>c.sale_id===editSaleId&&c.affiliate_id===client?.affiliateId);
 const referralRate=existing?Number(existing.commission_rate):ref?.affiliateStatus==='approved'&&ref.active!==false?Number(ref.commissionRate||0):0;
 const partnerRate=PartnerState.draft.reduce((n,d)=>n+Number(d.rate),0),referral=Math.round(value*referralRate)/100,partners=PartnerState.draft.reduce((n,d)=>n+Math.round(value*d.rate),0)/100;
 return {value,referralRate,partnerRate,referral,partners,remaining:Math.round((value-referral-partners)*100)/100};
}
function updatePartnerSplitSummary(){const host=document.getElementById('sale-partner-summary');if(!host)return;const s=getPartnerSplitSummary();host.innerHTML=`<div><span>Indicação · ${s.referralRate}%</span><strong>${partnerMoney(s.referral)}</strong></div><div><span>Parceiros · ${s.partnerRate}%</span><strong>${partnerMoney(s.partners)}</strong></div><div><span>Magemind · ${Number((100-s.referralRate-s.partnerRate).toFixed(2))}%</span><strong>${partnerMoney(s.remaining)}</strong></div>${s.partnerRate+s.referralRate>100||s.remaining<0?'<p role="alert">A soma das participações não pode ultrapassar o valor da venda.</p>':''}`;}
function validatePartnerDraft(){const s=getPartnerSplitSummary();if(PartnerState.draft.some(d=>!d.partner_id||!Number.isFinite(d.rate)||d.rate<=0||d.rate>100)||new Set(PartnerState.draft.map(d=>d.partner_id)).size!==PartnerState.draft.length||s.partnerRate+s.referralRate>100||s.remaining<0){toast('Revise os parceiros: sem repetições e com divisão total de até 100%.','err');return false;}return true;}
async function openPartnerWithdrawal(){
 try{await loadPartnerData();if(Number(partnerMetrics().available)<1){toast('Você ainda não tem saldo disponível para saque.','err');return;}PartnerState.withdrawKey=crypto.randomUUID();document.getElementById('pw-available').textContent=partnerMoney(partnerMetrics().available);document.getElementById('pw-amount').value='';document.getElementById('pw-key').value='';openModal('modal-partner-withdrawal');}catch(e){toast(e.message,'err');}
}
async function submitPartnerWithdrawal(button){
 button.disabled=true;try{const {error}=await supa.rpc('request_partner_withdrawal',{p_amount:Number(document.getElementById('pw-amount').value),p_type:document.getElementById('pw-type').value,p_key:document.getElementById('pw-key').value.trim(),p_request:PartnerState.withdrawKey});if(error)throw error;closeModal('modal-partner-withdrawal');PartnerState.tab='withdrawals';await refreshPartnerPanel();toast('Solicitação enviada para análise.','ok');}catch(e){toast(e.message,'err');}finally{button.disabled=false;}
}
let partnerReview=null;
function openPartnerReview(id,action){const w=PartnerState.withdrawals.find(w=>w.id===id);if(!w)return;partnerReview={id,action};const title={approve:'Aprovar saque',pay:'Registrar pagamento',reject:'Recusar saque',reverse:'Estornar registro de pagamento',cancel:'Cancelar solicitação'}[action];document.getElementById('pr-title').textContent=title;document.getElementById('pr-summary').textContent=`${w.partner_name} · ${partnerMoney(w.amount)}. ${action==='pay'?'Confirme somente depois de realizar o pagamento via Pix. Esta ação registra o pagamento no sistema.':action==='reverse'?'Este registro devolve o valor à carteira; não realiza movimentações bancárias.':'Confira os dados antes de confirmar.'}`;document.getElementById('pr-note').value='';openModal('modal-partner-review');}
async function submitPartnerReview(button){if(!partnerReview)return;button.disabled=true;try{const {error}=await supa.rpc('review_partner_withdrawal',{p_id:partnerReview.id,p_action:partnerReview.action,p_note:document.getElementById('pr-note').value.trim()});if(error)throw error;closeModal('modal-partner-review');await refreshPartnerPanel();toast('Solicitação atualizada.','ok');}catch(e){toast(e.message,'err');}finally{button.disabled=false;}}

// UI nodes exist before the accessibility module scans dialogs.
document.querySelector('.content').insertAdjacentHTML('beforeend','<div class="page" id="pg-partners"><div class="ph"><div class="ph-info"><div class="ph-title" id="partners-title">Parceiros</div><div class="ph-sub" id="partners-sub"></div></div></div><div id="partners-content" class="partner-content"></div></div>');

document.querySelector('#modal-sale .m-body').insertAdjacentHTML('beforeend','<section id="sale-partner-splits" class="sale-partner-splits" aria-label="Participações na venda"></section>');
document.body.insertAdjacentHTML('beforeend',`<div class="overlay" id="modal-partner-withdrawal" onclick="if(event.target===this)closeModal(this.id)"><div class="modal"><div class="m-head"><div class="m-title">Solicitar saque</div><button class="btn btn-ghost" aria-label="Fechar solicitação" onclick="closeModal('modal-partner-withdrawal')">✕</button></div><div class="m-body"><p>Disponível: <strong id="pw-available"></strong></p><label class="fg"><span class="fl">Valor do saque (R$)</span><input class="fi" id="pw-amount" type="number" min="1" step="0.01" inputmode="decimal"></label><label class="fg"><span class="fl">Tipo de chave Pix</span><select class="fi" id="pw-type"><option value="cpf">CPF</option><option value="cnpj">CNPJ</option><option value="email">E-mail</option><option value="phone">Telefone</option><option value="random">Aleatória</option></select></label><label class="fg"><span class="fl">Chave Pix</span><input class="fi" id="pw-key" maxlength="140" autocomplete="off"></label><p class="partner-help">O valor fica reservado até a análise. Você pode cancelar enquanto a solicitação estiver pendente.</p></div><div class="m-foot"><button class="btn btn-ghost" onclick="closeModal('modal-partner-withdrawal')">Voltar</button><button class="btn btn-primary" onclick="submitPartnerWithdrawal(this)">Solicitar saque</button></div></div></div><div class="overlay" id="modal-partner-review" onclick="if(event.target===this)closeModal(this.id)"><div class="modal"><div class="m-head"><div class="m-title" id="pr-title"></div><button class="btn btn-ghost" aria-label="Fechar análise" onclick="closeModal('modal-partner-review')">✕</button></div><div class="m-body"><p id="pr-summary"></p><label class="fg"><span class="fl">Observação / motivo</span><textarea class="fi" id="pr-note" maxlength="500" rows="3" placeholder="Obrigatório ao recusar ou estornar"></textarea></label></div><div class="m-foot"><button class="btn btn-ghost" onclick="closeModal('modal-partner-review')">Voltar</button><button class="btn btn-primary" onclick="submitPartnerReview(this)">Confirmar</button></div></div></div>`);
['s-value','s-client','s-status'].forEach(id=>document.getElementById(id)?.addEventListener('input',updatePartnerSplitSummary));
document.getElementById('s-plan')?.addEventListener('change',updatePartnerSplitSummary);
document.addEventListener('visibilitychange',()=>{if(!document.hidden&&typeof DB!=='undefined'&&DB.me&&(isPartner()||isAdmin()))refreshPartnerPanel();});
