begin;
create temporary table payment_test_ids(key text primary key,id uuid);
create temporary table payment_test_results(test text,passed boolean);
grant all on payment_test_ids,payment_test_results to authenticated;
insert into payment_test_ids select 'client-profile',p.id from public.profiles p join public.clients c on c.id=p.client_id
where p.role='client' and p.active and p.archived_at is null and c.archived_at is null and c.status='Ativo' and c.affiliate_id is null
and not exists(select 1 from public.sales s where s.client_id=c.id and s.status='Pendente') limit 1;
insert into payment_test_ids select 'client',client_id from public.profiles where id=(select id from payment_test_ids where key='client-profile');
insert into payment_test_ids select 'ceo',id from public.profiles where role='ceo' and active limit 1;
insert into payment_test_ids select 'manager',id from public.profiles where role='manager' and active limit 1;
with s as(insert into public.sales(client_id,service,value,status,sale_date) values((select id from payment_test_ids where key='client'),'Rollback payment A',369,'Pendente','2031-04-05') returning id) insert into payment_test_ids select 'sale-a',id from s;
with s as(insert into public.sales(client_id,service,value,status,sale_date) values((select id from payment_test_ids where key='client'),'Rollback payment B',631,'Pendente','2031-04-05') returning id) insert into payment_test_ids select 'sale-b',id from s;
insert into payment_test_results values('no reminder before local noon',private.generate_pending_payment_reminders_at('2031-04-05T14:59:00Z')=0);
select private.generate_pending_payment_reminders_at('2031-04-05T15:00:00Z');
insert into payment_test_results select 'one reminder with summed BRL amount at noon',count(*)=1 and bool_and(body like '%1.000,00%') from public.notifications where to_user_id=(select id from payment_test_ids where key='client-profile') and dedupe_key='payment:2031-04-05';
insert into payment_test_results values('repeat execution is idempotent',private.generate_pending_payment_reminders_at('2031-04-05T15:00:30Z')=0);
update public.sales set status='Fechado' where id in(select id from payment_test_ids where key in('sale-a','sale-b'));
select private.generate_pending_payment_reminders_at('2031-04-06T15:00:00Z');
insert into payment_test_results select 'closed payments stop reminders',not exists(select 1 from public.notifications where to_user_id=(select id from payment_test_ids where key='client-profile') and dedupe_key='payment:2031-04-06');
update public.sales set status=case when id=(select id from payment_test_ids where key='sale-a') then 'Pendente' else 'Cancelado' end where id in(select id from payment_test_ids where key in('sale-a','sale-b'));
select private.generate_pending_payment_reminders_at('2031-04-07T15:00:00Z');
insert into payment_test_results select 'canceled payments excluded from amount',count(*)=1 and bool_and(body like '%369,00%') from public.notifications where to_user_id=(select id from payment_test_ids where key='client-profile') and dedupe_key='payment:2031-04-07';
update public.sales set status='Cancelado' where id=(select id from payment_test_ids where key='sale-a');
select private.generate_pending_payment_reminders_at('2031-04-08T15:00:00Z');
insert into payment_test_results select 'canceled payments stop reminders',not exists(select 1 from public.notifications where to_user_id=(select id from payment_test_ids where key='client-profile') and dedupe_key='payment:2031-04-08');
select set_config('request.jwt.claims',jsonb_build_object('sub',(select id from payment_test_ids where key='ceo'),'role','authenticated')::text,true);
update public.profiles set role='gestor' where id=(select id from payment_test_ids where key='manager');
with d as(insert into public.demands(title,client_id,created_by) values('Regression client notification',(select id from payment_test_ids where key='client'),auth.uid()) returning id) insert into payment_test_ids select 'demand',id from d;
select set_config('request.jwt.claims',jsonb_build_object('sub',(select id from payment_test_ids where key='manager'),'role','authenticated')::text,true);
set local role authenticated;
insert into payment_test_results select 'gestor cannot read client profile',not exists(select 1 from public.profiles where id=(select id from payment_test_ids where key='client-profile'));
insert into payment_test_results values('gestor can notify the scoped client',cardinality(public.notify_client((select id from payment_test_ids where key='client'),'!','var(--amberbg)','Atualização','Regression rollback',(select id from payment_test_ids where key='demand'),'demand_updated'))=1);
reset role;
select set_config('request.jwt.claims',jsonb_build_object('sub',(select id from payment_test_ids where key='client-profile'),'role','authenticated')::text,true);
set local role authenticated;
insert into payment_test_results select 'client sees delivered in-app reminder',exists(select 1 from public.get_my_notifications() n where n->>'dedupe_key'='payment:2031-04-05');
insert into payment_test_results select 'client cannot read other clients sales',not exists(select 1 from public.sales where client_id<>(select id from payment_test_ids where key='client'));
reset role;
select jsonb_agg(to_jsonb(r)) as regression_results from payment_test_results r;
rollback;
